### ISSUE TITLE
Able to authenticate credentials but not getPositions

### ISSUE THREAD

**Issue by fruddq** [Qluxzz/avanza#56]
I receive the following error message:

TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "X-AuthenticationSession"
    at ClientRequest.setHeader (node:_http_outgoing:579:3)
    at new ClientRequest (node:_http_client:262:14)
    at Object.request (node:https:353:10)
    at /home/frudd/Coding/tensai-vexa-api/node_modules/avanza-lib/dist/index.js:53:23
    at new Promise (<anonymous>)
    at request (/home/frudd/Coding/tensai-vexa-api/node_modules/avanza-lib/dist/index.js:52:10)
    at /home/frudd/Coding/tensai-vexa-api/node_modules/avanza-lib/dist/index.js:934:9
    at new Promise (<anonymous>)
    at Avanza.call (/home/frudd/Coding/tensai-vexa-api/node_modules/avanza-lib/dist/index.js:930:12)
    at Avanza.getPositions (/home/frudd/Coding/tensai-vexa-api/node_modules/avanza-lib/dist/index.js:600:17) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}

**Comment by Qluxzz** [comment]
You seem to be using the JavaScript library described here https://github.com/fhqvst/avanza, this is a Python library
